### ISSUE TITLE
Unable to edit .sql files

### ISSUE THREAD

**Issue by hayian** [mohamicorp/editor-for-stash-issues#9] opened 2015-06-30 06:35 UTC
When trying to edit a sql file it's unable to present it properly:

![capture](https://cloud.githubusercontent.com/assets/13113861/8425111/e6764620-1f45-11e5-8f89-571ab60f6c4a.PNG)

**Comment by mdavoodi** [comment] 2015-07-01 06:26
I'm unable to reproduce this. Could you give me your stash version and browser version?

Maybe you could reproduce this with an example file and post it here?

**Comment by hayian** [comment] 2015-07-01 13:13
hmm, it seems to be something with this particular sql file, others open ok.  I can't really post the code so I'll see if I can nut out what is causing it within the sql file and let you know.

I've tested it in IE11 and Chrome 43 with Stash 3.10.0.

**Comment by hayian** [comment] 2015-07-02 01:14
It looks like it was some sort of encoding or corruption in a few SQL files.  They work fine from notepad++ and most other apps, but even Stash was having problems doing a diff before merging.  Deleting the files and recreating them seems to have fixed the problem.

**Comment by mdavoodi** [comment] 2015-07-06 08:15
I made a new issue ticket regarding bad file detection so I'm going to close this.

**Closed as completed by mdavoodi** 2015-07-06 08:15 UTC
Labels: bug
