### ISSUE TITLE
Regression in 3.10.2: Non-Admin user 401's when editing.

### ISSUE THREAD

**Issue by at3560k** [mohamicorp/editor-for-stash-issues#13] opened 2015-07-09 20:28 UTC
Hi, can you confirm that this plugin works as intended with non-admin (regular users with repository write access) in Stash 3.10.2 ?

  I just took a bit this afternoon testing the plugin in some different data center/non data center configurations, and have come to the conclusion that users without _admin_ on a brand new stash install.

https://bitbucket.org/nicolapaolucci/stash-vagrant-install.git  (bumped the manifests/default.pp version to 3.10.2 and 3.9.2 to test)

Steps to reproduce:

1 ) Brand new stash 3.10.2 install
2) Create test project, containing test repository
3) Create your  'admin' user (have to to do the rest) and a 'local' non admin user
4) Create and initialize new repository, give the non admin user write access
5) As local user, push a hello world to the repository 
6) Log in as 'local' user and click the edit button -- get a 401 every time in 3.10.2 but not in 3.9.2

If I'm very lucky I may have curl  to reproduce this later.

**Comment by matthewbarr** [comment] 2015-07-12 04:37
@mdavoodi We're looking at this plugin for about 2000 users, and right now it doesn't work..

**Comment by mdavoodi** [comment] 2015-07-12 05:31
We're are currently looking at this. Expect a fix ASAP.

**Comment by matthewbarr** [comment] 2015-07-12 05:33
Wasn't sure you could replicate it.  Thanks!

**Comment by mdavoodi** [comment] 2015-07-13 04:26
This bug was caused by https://jira.atlassian.com/browse/STASH-7521 and it's been fixed in version 1.4.2.

**Closed as completed by mdavoodi** 2015-07-13 04:26 UTC
Labels: bug

**Comment by matthewbarr** [comment] 2015-07-13 04:41
Odd.  it looked like the bug was closed in 3.10.2, but maybe that caused the issue.  We'll test 1.4.2...

Thanks!
